channel_sources:
  - conda-forge/label/microed-data_dev,conda-forge
channel_targets:
  - conda-forge tvips-tools_dev
c_compiler:          # [win]
  - m2w64-toolchain  # [win]
cxx_compiler:        # [win]
  - m2w64-toolchain  # [win]
target_platform:     # [win]
  - win-64           # [win]
