{% set name = "TVIPS tools" %}
{% set tarname = name|lower|replace(' ', '-') %}
{% set version = "0.0.1-dev.1" %}

package:
  name: {{ tarname }}
  version: {{ version|replace('-dev.', '.dev') }}

source:
  url: https://cryoem.ucla.edu/downloads/{{ tarname }}-{{ version }}.tar.gz
  sha256: d51820ce2e2586aac78801c05a16d48c2d99dfa870819d0af87d71252207ec77
  patches:
    - 01-setenv.patch
    - 02-version.patch
    - 03-install.patch
    - 04-warnings.patch

build:
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=2.8.5,<4
    - coreutils
    - libxslt >=0.13.0
    - make
  host:
    - libtiff 4.*
  run:
    - {{ pin_compatible('libtiff', max_pin='x.x') }}

test:
  requires:
    - coreutils
  source_files:
    - test/*.tif
    - test/*.tvips

about:
  home: https://cryoem.ucla.edu/microed
  license: ISC
  license_file: LICENSE
  summary: "Convert diffraction images from TVIPS format to SMV"
  description: |
    The TVIPS tools convert sequences of related electron diffraction
    images, or MicroED sweeps, recorded by Tietz Video and Image
    Processing Systems (TVIPS) cameras to the Super Marty View (SMV)
    format.

extra:
  recipe-maintainers:
    - hattne
