{% set name = "TVIPS tools" %}
{% set tarname = name|lower|replace(' ', '-') %}
{% set version = "0.1.0-dev.0" %}

package:
  name: {{ tarname }}
  version: {{ version|replace('-dev.', '.dev') }}

source:
  url: https://cryoem.ucla.edu/downloads/{{ tarname }}-{{ version }}.tar.gz
  sha256: 3594e63ec86d60113b80aaf2353c6bc7e951738941bd2cdaab60ac7a7affb024
  patches:
    - 01-setenv.patch
    - 02-version.patch
    - 03-install.patch
    - 04-test.patch
    - 05-disable-libR.patch
    - 06-err_h.patch
    - 07-windows.patch
    - 08-cmake.patch
    - 09-warnings.patch

build:
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
  number: 0
  script_env:
    - USER      # [unix]
    - USERNAME  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake   >=3.2,<4
    - coreutils         # [unix]
    - m2-coreutils      # [win]
    - libxslt >=0.13.0
    - make              # [unix]
  host:
    - libtiff 4.*
  run:
    - {{ pin_compatible('libtiff', max_pin='x.x') }}

test:
  requires:
    - coreutils     # [unix]
    - m2-coreutils  # [win]
    - m2-sed        # [win]
  source_files:
    - test/*.tif
    - test/*.tvips

about:
  home: https://cryoem.ucla.edu/microed
  license: ISC
  license_file: LICENSE
  summary: "Convert diffraction images from TVIPS format to SMV"
  description: |
    The TVIPS tools convert sequences of related electron diffraction
    images, or MicroED sweeps, recorded by Tietz Video and Image
    Processing Systems (TVIPS) cameras to the Super Marty View (SMV)
    format.

extra:
  recipe-maintainers:
    - hattne
