{% set name = "TVIPS tools" %}
{% set tarname = name|lower|replace(' ', '-') %}
{% set version = "0.0.1-dev.2" %}

package:
  name: {{ tarname }}
  version: {{ version|replace('-dev.', '.dev') }}

source:
  url: https://cryoem.ucla.edu/downloads/{{ tarname }}-{{ version }}.tar.gz
  sha256: 540a1172c651c70f44d96cdef29839c692598a5d088abcab94ab6f9398d6ada5
  patches:
    - 01-setenv.patch
    - 02-version.patch
    - 03-install.patch
    - 04-warnings.patch

build:
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=2.8.5,<4
    - coreutils     # [unix]
    - libxslt >=0.13.0
    - make          # [unix]
  host:
    - libtiff 4.*
  run:
    - {{ pin_compatible('libtiff', max_pin='x.x') }}

test:
  requires:
    - coreutils     # [unix]
    - m2-coreutils  # [win]
    - m2-sed        # [win]
  source_files:
    - test/*.tif
    - test/*.tvips

about:
  home: https://cryoem.ucla.edu/microed
  license: ISC
  license_file: LICENSE
  summary: "Convert diffraction images from TVIPS format to SMV"
  description: |
    The TVIPS tools convert sequences of related electron diffraction
    images, or MicroED sweeps, recorded by Tietz Video and Image
    Processing Systems (TVIPS) cameras to the Super Marty View (SMV)
    format.

extra:
  recipe-maintainers:
    - hattne
